spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/schoolback?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: samuel
    password: samuel
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
server:
  port:
    ${port:8080}
security:
  basic:
    enabled: false
  ignored:
    - /**